Import the package for learning and modeling trees

In [1]:
from sklearn import tree 

Define the matrix containing the data (one example per row)
and the vector containing the corresponding target value

In [2]:
X = [[0, 0, 0], [1, 1, 1], [0, 1, 0], [0, 0, 1], [1, 1, 0], [1, 0, 1]]
Y = [1, 0, 0, 0, 1, 1]

Declare the classification model you want to use and then fit the model to the data

In [3]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X, Y)

Predict the target value (and print it) for the passed data, using the fitted model currently in clf

In [4]:
print(clf.predict([[0, 1, 1]]))

[0]


In [5]:
print(clf.predict([[1, 0, 1],[0, 0, 1]]))

[1 0]


In [7]:
import graphviz 
dot_data = tree.export_graphviz(clf, out_file=None)  
graph = graphviz.Source(dot_data)  
graph

ExecutableNotFound: failed to execute ['dot', '-Tsvg'], make sure the Graphviz executables are on your systems' PATH

In the following we start using a dataset (from UCI Machine Learning repository)

In [8]:
from sklearn.datasets import load_iris
iris = load_iris()


# Declare the type of prediction model and the working criteria for the model induction algorithm

In [9]:
clf = tree.DecisionTreeClassifier(criterion="entropy",random_state=300,min_samples_leaf=5,class_weight={0:1,1:1,2:1})

# Split the dataset in training and test set

In [68]:
# Generate a random permutation of the indices of examples that will be later used 
# for the training and the test set
import numpy as np
np.random.seed(0)
indices = np.random.permutation(len(iris.data))

# We now decide to keep the last 10 indices for test set, the remaining for the training set
indices_training=indices[:-10]
indices_test=indices[-10:]

iris_X_train = iris.data[indices_training] # keep for training all the matrix elements with the exception of the last 10 
iris_y_train = iris.target[indices_training]
iris_X_test  = iris.data[indices_test] # keep the last 10 elements for test set
iris_y_test  = iris.target[indices_test]

[114  62  33 107   7 100  40  86  76  71 134  51  73  54  63  37  78  90
  45  16 121  66  24   8 126  22  44  97  93  26 137  84  27 127 132  59
  18  83  61  92 112   2 141  43  10  60 116 144 119 108  69 135  56  80
 123 133 106 146  50 147  85  30 101  94  64  89  91 125  48  13 111  95
  20  15  52   3 149  98   6  68 109  96  12 102 120 104 128  46  11 110
 124  41 148   1 113 139  42   4 129  17  38   5  53 143 105   0  34  28
  55  75  35  23  74  31 118  57 131  65  32 138  14 122  19  29 130  49
 136  99  82  79 115 145  72  77  25  81 140 142  39  58]


# Fit the learning model on training set

In [11]:
# fit the model to the training data
clf = clf.fit(iris_X_train, iris_y_train)

# Obtain predictions

In [12]:
# apply fitted model "clf" to the test set 
predicted_y_test = clf.predict(iris_X_test)

# print the predictions (class numbers associated to classes names in target names)
print("Predictions:")
print(predicted_y_test)
print("True classes:")
print(iris_y_test) 
print(iris.target_names)

Predictions:
[1 2 1 0 0 0 2 1 2 0]
True classes:
[1 1 1 0 0 0 2 1 2 0]
['setosa' 'versicolor' 'virginica']


# Print the index of the test instances and the corresponding predictions

# Look at the specific examples

In [13]:
for i in range(len(iris_y_test)): 
    print("Instance # "+str(indices_test)+": ")
    s=""
    for j in range(len(iris.feature_names)):
        s=s+iris.feature_names[j]+"="+str(iris_X_test[i][j])
        if (j<len(iris.feature_names)-1): s=s+", "
    print(s)
    print("Predicted: "+iris.target_names[predicted_y_test[i]]+"\t True: "+iris.target_names[iris_y_test[i]]+"\n")

Instance # [ 88  70  87  36  21   9 103  67 117  47]: 
sepal length (cm)=5.6, sepal width (cm)=3.0, petal length (cm)=4.1, petal width (cm)=1.3
Predicted: versicolor	 True: versicolor

Instance # [ 88  70  87  36  21   9 103  67 117  47]: 
sepal length (cm)=5.9, sepal width (cm)=3.2, petal length (cm)=4.8, petal width (cm)=1.8
Predicted: virginica	 True: versicolor

Instance # [ 88  70  87  36  21   9 103  67 117  47]: 
sepal length (cm)=6.3, sepal width (cm)=2.3, petal length (cm)=4.4, petal width (cm)=1.3
Predicted: versicolor	 True: versicolor

Instance # [ 88  70  87  36  21   9 103  67 117  47]: 
sepal length (cm)=5.5, sepal width (cm)=3.5, petal length (cm)=1.3, petal width (cm)=0.2
Predicted: setosa	 True: setosa

Instance # [ 88  70  87  36  21   9 103  67 117  47]: 
sepal length (cm)=5.1, sepal width (cm)=3.7, petal length (cm)=1.5, petal width (cm)=0.4
Predicted: setosa	 True: setosa

Instance # [ 88  70  87  36  21   9 103  67 117  47]: 
sepal length (cm)=4.9, sepal width (c

In [14]:
# print the corresponding instances indexes and class names 
for i in range(len(iris_y_test)): 
    print("Instance # "+str(indices_test[i])+": ")
    print("Predicted: "+iris.target_names[predicted_y_test[i]]+"\t True: "+iris.target_names[iris_y_test[i]]+"\n")

Instance # 88: 
Predicted: versicolor	 True: versicolor

Instance # 70: 
Predicted: virginica	 True: versicolor

Instance # 87: 
Predicted: versicolor	 True: versicolor

Instance # 36: 
Predicted: setosa	 True: setosa

Instance # 21: 
Predicted: setosa	 True: setosa

Instance # 9: 
Predicted: setosa	 True: setosa

Instance # 103: 
Predicted: virginica	 True: virginica

Instance # 67: 
Predicted: versicolor	 True: versicolor

Instance # 117: 
Predicted: virginica	 True: virginica

Instance # 47: 
Predicted: setosa	 True: setosa



# Obtain model performance results

In [15]:
# print some metrics results
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
acc_score = accuracy_score(iris_y_test, predicted_y_test)
print("Accuracy score: "+ str(acc_score))
f1=f1_score(iris_y_test, predicted_y_test, average='macro')
print("F1 score: "+str(f1))

Accuracy score: 0.9
F1 score: 0.8857142857142858


# Use Cross Validation

In [16]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score # will be used to separate training and test
iris = load_iris()
clf = tree.DecisionTreeClassifier(criterion="entropy",random_state=300,min_samples_leaf=5,class_weight={0:1,1:1,2:1})
clf = clf.fit(iris.data, iris.target)
scores = cross_val_score(clf, iris.data, iris.target, cv=5) # score will be the accuracy
print(scores)

[0.96666667 1.         0.86666667 0.86666667 1.        ]


In [17]:
# computes F1- score
f1_scores = cross_val_score(clf, iris.data, iris.target, cv=5, scoring='f1_macro')
print(f1_scores)

[0.96658312 1.         0.86111111 0.86666667 1.        ]


# Show the resulting tree 

## 1. Print the picture in a PDF file

In [5]:
import graphviz
def print_model_in_pdf_file(clf,name_file):
    dot_data = tree.export_graphviz(clf, out_file=None) 
    graph = graphviz.Source(dot_data) 
    graph.render(name_file)
    dot_data = tree.export_graphviz(clf, out_file=None, 
                         feature_names=iris.feature_names, 
                         class_names=iris.target_names, 
                         filled=True, rounded=True,  
                         special_characters=True)  
    graph = graphviz.Source(dot_data)  
    return graph

## 2. Generate a picture here

In [12]:
print(list(iris.feature_names))
print(list(iris.target_names))

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa', 'versicolor', 'virginica']


In [17]:
print_model_in_pdf_file(clf,"my_iris_predictions")

ExecutableNotFound: failed to execute ['dot', '-Tpdf', '-O', 'my_iris_predictions'], make sure the Graphviz executables are on your systems' PATH

# Your work: what you have to do
Modify the given Jupyter notebook on decision trees on Iris data and perform the following tasks:

1. get an artificial inflation of some class in the training set by a given factor: 10 (weigh more the classes virginica e versicolor which are more difficult to discriminate). Learn the tree in these conditions. (Moltiplicare il numero di esempi delle classi virgnica e versicolor)

1.b) modify the weight of some classes (set to 10 the weights for misclassification between virginica into versicolor and vice versa) and learn the tree in these conditions. You should obtain similar results as for step 1.


2. learn trees but try to avoid overfitting (by improving the error on the test set) tuning the hyper-parameters on: the minimum number of samples per leaf, max depth of the tree, min_impurity_decrease parameters, max leaf nodes, etc.


3. build the confusion matrix of the created tree models on the test set and show them. 


4. build the ROC curves (or coverage curves in coverage space) and plot them for each tree model you have created: for each model you have to build three curves, one for each class, considered in turn as the positive class.

# Artificial inflation

In [85]:
from sklearn import tree 
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
import numpy as np
from sklearn.metrics import roc_auc_score,roc_curve

iris = load_iris()

clf1 = tree.DecisionTreeClassifier(criterion="entropy",random_state=300,min_samples_leaf=5,class_weight={0:1,1:1,2:1})
clf2 = tree.DecisionTreeClassifier(criterion="entropy",random_state=300,min_samples_leaf=5,class_weight={0:1,1:10,2:10})


# INFLAZIONE ARTIFICIALE DELLE CLASSI VIRGINIA e VERSICOLOR

new_dataset_X_train = iris.data
new_dataset_y_train = iris.target


for i in range(len(iris.data)):
    if iris.target[i] == 1 or iris.target[i] == 2:
        for j in range(10):
            new_dataset_X_train = np.append(new_dataset_X_train,[iris.data[i]],0)
            new_dataset_y_train = np.append(new_dataset_y_train,iris.target[i])

print(len(new_dataset_X_train))
print(len(new_dataset_y_train))
np.random.seed(0)
indices = np.random.permutation(len(new_dataset_X_train))

# We now decide to keep the last 10 indices for test set, the remaining for the training set
indices_training=indices[:-10]
indices_test=indices[-10:]

iris_X_train = new_dataset_X_train[indices_training] # keep for training all the matrix elements with the exception of the last 10 
iris_y_train = new_dataset_y_train[indices_training]
iris_X_test  = new_dataset_X_train[indices_test] # keep the last 10 elements for test set
iris_y_test  = new_dataset_y_train[indices_test]

clf1.fit(iris_X_train,iris_y_train)
clf2.fit(iris_X_train,iris_y_train)

# apply fitted model "clf" to the test set 
predicted_y_test1 = clf1.predict(iris_X_test)
predicted_y_test2 = clf2.predict(iris_X_test)

# print the predictions (class numbers associated to classes names in target names)
print("Predictions TEST:")
print(predicted_y_test1)
print("True classes:")
print(iris_y_test) 
print(iris.target_names)

acc_score = accuracy_score(iris_y_test, predicted_y_test1)
print("Accuracy score: "+ str(acc_score))
f1=f1_score(iris_y_test, predicted_y_test1, average='macro')
print("F1 score: "+str(f1))

# print the predictions (class numbers associated to classes names in target names)
print("Predictions TEST 2:")
print(predicted_y_test2)
print("True classes:")
print(iris_y_test) 
print(iris.target_names)



acc_score = accuracy_score(iris_y_test, predicted_y_test2)
print("Accuracy score: "+ str(acc_score))
f1=f1_score(iris_y_test, predicted_y_test2, average='macro')
print("F1 score: "+str(f1))

#print_model_in_pdf_file(clf1,"artifical n1")
#print_model_in_pdf_file(clf2,"artifical n2")


1150
1150
Predictions TEST:
[1 1 2 1 1 2 2 2 1 2]
True classes:
[1 1 2 1 1 2 2 2 1 2]
['setosa' 'versicolor' 'virginica']
Accuracy score: 1.0
F1 score: 1.0
Predictions TEST 2:
[1 1 2 1 1 2 2 2 1 2]
True classes:
[1 1 2 1 1 2 2 2 1 2]
['setosa' 'versicolor' 'virginica']
Accuracy score: 1.0
F1 score: 1.0


# Build confusion matrix

In [22]:
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import itertools

def draw_confusion_matrix(iris_y_test,predicted_y_test):
    class_names = iris.target_names
    y_true = iris.target
    cf = confusion_matrix(iris_y_test,predicted_y_test)
    plt.figure()
    plt.imshow(cf, cmap=plt.cm.Blues)
    plt.title("Confusion Matrix")
    plt.ylabel("True Label")
    plt.xlabel("Predicted Label")

    tick_marks = np.arange(len(class_names))
    plt.xticks(tick_marks, class_names)
    plt.yticks(tick_marks, class_names)

    thresh = cf.max() / 2.0
    for i, j in itertools.product(range(cf.shape[0]),range(cf.shape[1])):
        plt.text(j, i, cf[i, j],horizontalalignment="center",color="white" if cf[i, j] > thresh else "black",)
    plt.colorbar()
    plt.show()

draw_confusion_matrix(iris_y_test,predicted_y_test1)
draw_confusion_matrix(iris_y_test,predicted_y_test2)


# Try to avoid overfitting

In [23]:
import numpy as np
import matplotlib.pyplot as plt
from itertools import cycle
 
from sklearn import tree,svm, datasets
from sklearn.metrics import roc_curve, auc,roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize

iris = datasets.load_iris()

np.random.seed(2)
indices = np.random.permutation(len(iris.data))

# We now decide to keep the last 10 indices for test set, the remaining for the training set
indices_training=indices[:-10]
indices_test=indices[-10:]

iris_X_train = iris.data[indices_training] # keep for training all the matrix elements with the exception of the last 10 
iris_y_train = iris.target[indices_training]
iris_X_test  = iris.data[indices_test] # keep the last 10 elements for test set
iris_y_test  = iris.target[indices_test]

clf_of = tree.DecisionTreeClassifier(criterion="entropy",random_state=0,min_samples_leaf=5,max_depth=3,class_weight={0:1,1:1,2:1})
clf_of.fit(iris_X_train,iris_y_train)
predicted_y_test_of = clf_of.predict(iris_X_test)

# print the predictions (class numbers associated to classes names in target names)
print("Predictions TEST:")
print(predicted_y_test_of)
print("True classes:")
print(iris_y_test) 
print(iris.target_names)

acc_score_of = accuracy_score(iris_y_test, predicted_y_test_of)
print("Accuracy score: "+ str(acc_score_of))
f1_of=f1_score(iris_y_test, predicted_y_test_of, average='macro')
print("F1 score: "+str(f1_of))

Predictions TEST:
[0 2 1 0 2 1 0 0 1 0]
True classes:
[0 2 1 0 2 1 0 0 1 0]
['setosa' 'versicolor' 'virginica']
Accuracy score: 1.0
F1 score: 1.0


# Draw roc curve

In [8]:
import numpy as np
import matplotlib.pyplot as plt
from itertools import cycle
 
from sklearn import tree,svm, datasets
from sklearn.metrics import roc_curve, auc,roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize


iris = datasets.load_iris()

def split_binary_dataset(iris,positive_label):
    y = iris.target
    for i in range(len(iris.target)):
        if iris.target[i] == positive_label:
            y[i] = 1
        else:
            y[i] = 0
    return y


def draw_roc_curve(y_test1,predicted_y_test1,y_test2,predicted_y_test2,y_test3,predicted_y_test3):
    fpr, tpr, _ = roc_curve(y_test1, predicted_y_test1)
    roc_auc = auc(fpr, tpr)
    plt.figure()
    plt.plot(fpr, tpr, label="Setosa (area = %0.2f)" % roc_auc)
    fpr, tpr, _ = roc_curve(y_test2, predicted_y_test2)
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label="Versicolor (area = %0.2f)" % roc_auc)
    fpr, tpr, _ = roc_curve(y_test3, predicted_y_test3)
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label="Virginica (area = %0.2f)" % roc_auc)
    plt.plot([0, 1], [0, 1], "k")
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.title("ROC")
    plt.legend(loc="lower right")
    plt.show()
    
first_case_X = iris.data
first_case_y = split_binary_dataset(iris,0)

np.random.seed(0)
indices = np.random.permutation(len(iris.data))

indices_training = indices[:-10]
indices_test = indices[-10:]

X_train1 = first_case_X[indices_training]
y_train1 = first_case_y[indices_training]
X_test1 = first_case_X[indices_test]
y_test1 = first_case_y[indices_test]

clf = tree.DecisionTreeClassifier(criterion="entropy",random_state=300,min_samples_leaf=5,class_weight={0:1,1:1})
clf.fit(X_train1,y_train1)

predicted_y_train1 = clf.predict_proba(X_train1)[:, 1]
predicted_y_test1 = clf.predict_proba(X_test1)[:, 1]

auc_train = roc_auc_score(y_train1,predicted_y_train1)
auc_test = roc_auc_score(y_test1,predicted_y_test1)


iris = datasets.load_iris()
second_case_X = iris.data
second_case_y = split_binary_dataset(iris,1)

np.random.seed(0)
indices = np.random.permutation(len(iris.data))

indices_training = indices[:-10]
indices_test = indices[-10:]

X_train2 = second_case_X[indices_training]
y_train2 = second_case_y[indices_training]
X_test2 = second_case_X[indices_test]
y_test2 = second_case_y[indices_test]

clf = tree.DecisionTreeClassifier(criterion="entropy",random_state=300,min_samples_leaf=5,class_weight={0:1,1:1})
clf.fit(X_train2,y_train2)

predicted_y_train2 = clf.predict_proba(X_train2)[:, 1]
predicted_y_test2 = clf.predict_proba(X_test2)[:, 1]

auc_train = roc_auc_score(y_train2,predicted_y_train2)
auc_test = roc_auc_score(y_test2,predicted_y_test2)

print("Training AUC: ")
print(auc_train)
print("Test AUC: ")
print(auc_test)

iris = datasets.load_iris()
third_case_X = iris.data
third_case_y = split_binary_dataset(iris,2)

np.random.seed(0)
indices = np.random.permutation(len(iris.data))

indices_training = indices[:-10]
indices_test = indices[-10:]

X_train3 = third_case_X[indices_training]
y_train3 = third_case_y[indices_training]
X_test3 = third_case_X[indices_test]
y_test3 = third_case_y[indices_test]

clf = tree.DecisionTreeClassifier(criterion="entropy",random_state=300,min_samples_leaf=5,class_weight={0:1,1:1})
clf.fit(X_train3,y_train3)

predicted_y_train3 = clf.predict_proba(X_train3)[:, 1]
predicted_y_test3 = clf.predict_proba(X_test3)[:, 1]

auc_train = roc_auc_score(y_train3,predicted_y_train3)
auc_test = roc_auc_score(y_test3,predicted_y_test3)

print("Training AUC: ")
print(auc_train)
print("Test AUC: ")
print(auc_test)

draw_roc_curve(y_test1,predicted_y_test1,y_test2,predicted_y_test2,y_test3,predicted_y_test3)

Training AUC: 
0.9981498612395929
Test AUC: 
0.875
Training AUC: 
0.9981884057971016
Test AUC: 
0.9375
